#ifndef GLOBALS_H
#define GLOBALS_H

#define DICT_NAME_MAX_SIZE 255
#define MAX_PATH_NAME_LEN 64
#define MAX_PLUGINS_ALLOWED 10
#define MAX_STRING_LEN 32

typedef enum errors_e 
{
	EUNDEFINED = 0,
	EOK,
	ECHAR_OVERFLOW,
	EPLUGIN_OVERFLOW,
	ELANGUAGE_NAME_ERR,
	ETRANSLATE_ERR,
	ECLOSELIB_ERR,
	EWRONG_PARAMETER,
	EMAX
} errors_t;

#endif
